site_name: RH OVE Multi-Cluster Ecosystem
site_description: Red Hat OpenShift Virtualization Engine Multi-Cluster Architecture and Management
site_author: Professional Team
site_url: https://brunseba.github.io/rh-ove-ecosystem/
repo_name: brunseba/rh-ove-ecosystem
repo_url: https://github.com/brunseba/rh-ove-ecosystem

theme:
  name: material
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
  icon:
    repo: fontawesome/brands/github
    logo: material/cloud-outline

plugins:
  - search
  - mermaid2:
      arguments:
        theme: base
  - git-revision-date-localized:
      enable_creation_date: true
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture:
    - Context Diagram: architecture/context-diagram.md
    - Global Overview: architecture/global-overview.md
    - Single Cluster Overview: architecture/overview.md
    - Design Principles: architecture/design-principles.md
    - Network Architecture: architecture/network.md
    - Storage Architecture: architecture/storage.md
    - IAM Strategy: architecture/iam.md
    - ADRs:
      - ADR Table: architecture/adr/adr-table.md
      - ADR-001 Multi-Cluster Pattern: architecture/adr/adr-001-multi-cluster-pattern.md
      - ADR-002 GitOps ArgoCD: architecture/adr/adr-002-gitops-argocd.md
      - ADR-003 Cluster Topology: architecture/adr/adr-003-cluster-topology.md
      - ADR-004 Admission Controller: architecture/adr/adr-004-admission-controller.md
      - ADR-005 Network CNI: architecture/adr/adr-005-network-cni.md
      - ADR-006 Backup Strategy: architecture/adr/adr-006-backup-strategy.md
      - ADR-007 Monitoring Strategy: architecture/adr/adr-007-monitoring-strategy.md
      - ADR-008 IAM Strategy: architecture/adr/adr-008-iam-strategy.md
    - Requirements:
      - Requirements Table: architecture/requirements/requirements-table.md
      - Functional Requirements: architecture/requirements/fr.md
      - Non-Functional Requirements: architecture/requirements/nfr.md
  - Deployment:
    - Prerequisites: deployment/prerequisites.md
    - Installation Guide: deployment/installation.md
    - Configuration: deployment/configuration.md
  - Management:
    - Admission Control: management/admission-control.md
    - GitOps Operations: management/gitops.md
    - Monitoring: management/monitoring.md
    - Backup & Recovery: management/backup.md
  - Operations:
    - Day-2 Operations: operations/day2-ops.md
    - Troubleshooting: operations/troubleshooting.md
    - Performance Tuning: operations/performance.md
  - Use Cases:
    - Overview: use-cases/overview.md
    - 'Summary Table': use-cases/use-cases-table.md
    - VM Lifecycle:
      - VM Import & Migration: use-cases/vm-importation.md
      - VM Template Management: use-cases/vm-template-management.md
      - VM Scaling & Performance: use-cases/vm-scaling-performance.md
      - VM Backup & Recovery: use-cases/vm-backup-recovery.md
    - Application Deployment:
      - Hybrid Applications: use-cases/hybrid-applications.md
      - Multi-Environment Setup: use-cases/setup-multi-env-application.md
    - PaaS Integration:
      - Database Services: use-cases/database-services-paas.md
    - Enterprise Integration:
      - Legacy Modernization: use-cases/legacy-modernization.md
      - Disaster Recovery: use-cases/disaster-recovery.md
    - Observability:
      - End-to-End Observability: use-cases/end-to-end-observability.md
    - Security:
      - WAF & Firewalling: use-cases/waf-firewalling.md
    - Integration:
      - Events to CMDB/SIEM: use-cases/publishing-events-to-cmdb-siem.md
  - Project Plan:
    - Overview: project-plan/rh-ove-ecosystem-project-plan.md
    - Detailed Timeline: project-plan/detailed-project-timeline.md
    - Infrastructure Plan: project-plan/rh-ove-infrastructure-project-plan.md
    - Use-Cases Plan: project-plan/use-cases-implementation-project-plan.md
    - Migration Plan: project-plan/migration-workload-project-plan.md
    - Personas: project-plan/personas.md
    - RACI Matrix: project-plan/raci-matrix.md
    - Risk Register: project-plan/risk-register.md
    - Budget Estimate: project-plan/budget-estimate.md
    - Sizing Plan: project-plan/sizing-plan.md
    - Weekly Charge Breakdown: project-plan/weekly-charge-breakdown.md
  
  - References:
    - Product URLs: references/product-urls.md
    - Best Practices: references/best-practices.md
    - SBOM: references/sbom.md
    - Downloads: references/downloads.md
    - Task Management: TASKS.md
    - Glossary: references/glossary.md

extra:
  generator: false
  version:
    provider: mike
    default: latest
  tags:
    Multi-Cluster: multi-cluster
    Management: management
    Application: application
    Networking: networking
    Security: security
    GitOps: gitops
    Virtualization: virtualization
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/brunseba/rh-ove-ecosystem
      name: GitHub Repository
    - icon: fontawesome/brands/redhat
      link: https://redhat.com/
      name: Red Hat
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/
      name: LinkedIn
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
